services:
  app:
    build: .
    ports:
      - "80:8000"
    volumes:
      - ./data:/app/backend/data
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
